/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the current health status of the API and its dependencies.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload and index a PDF document
         * @description Upload a PDF file, extract its text, split into overlapping chunks,
         *     generate embeddings and persist them in ChromaDB.
         */
        post: operations["upload_document_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all indexed documents and collection stats */
        get: operations["list_documents_documents__get"];
        put?: never;
        post?: never;
        /** Clear the entire collection (all documents) */
        delete: operations["clear_collection_documents__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{pdf_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove all chunks belonging to a specific PDF */
        delete: operations["delete_document_documents__pdf_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Semantic search — retrieve relevant chunks
         * @description Performs a pure semantic search and returns the most relevant text chunks
         *     **without** calling the LLM. Useful for inspecting retrieved context.
         */
        post: operations["semantic_search_search__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask a question — search + LLM answer
         * @description Full RAG pipeline:
         *     1. Semantic search to retrieve the most relevant chunks.
         *     2. Pass chunks as context to the GROQ LLM.
         *     3. Return the generated answer along with metadata.
         */
        post: operations["ask_search_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AskRequest
         * @description Subclass of QueryRequest so `/search` and `/search/ask` share a single
         *     source of field definitions (they cannot drift apart) while keeping a
         *     distinct schema name in the OpenAPI document.
         */
        AskRequest: {
            /**
             * Query
             * @description Pergunta sobre os documentos
             */
            query: string;
            /**
             * N Results
             * @description Número de chunks a recuperar
             * @default 5
             */
            n_results: number;
            /**
             * Source Filter
             * @description Filtrar por nome do arquivo PDF
             */
            source_filter?: string | null;
        };
        /** AskResponse */
        AskResponse: {
            /** Query */
            query: string;
            /** Answer */
            answer: string;
            /** Sources */
            sources: string[];
            /** Chunks Used */
            chunks_used: number;
            /** Model */
            model: string;
        };
        /** Body_upload_document_documents_upload_post */
        Body_upload_document_documents_upload_post: {
            /**
             * File
             * @description PDF file to upload and index
             */
            file: string;
        };
        /** ChunkResult */
        ChunkResult: {
            /** Text */
            text: string;
            metadata: components["schemas"]["DocumentMetadata"];
            /** Distance */
            distance?: number | null;
        };
        /** CollectionStatsResponse */
        CollectionStatsResponse: {
            /** Total Chunks */
            total_chunks: number;
            /** Collection Name */
            collection_name: string;
            /** Persist Directory */
            persist_directory: string;
            /** Documents */
            documents?: string[];
        };
        /** DeleteDocumentResponse */
        DeleteDocumentResponse: {
            /** Success */
            success: boolean;
            /** Pdf Name */
            pdf_name: string;
            /** Chunks Deleted */
            chunks_deleted: number;
            /** Message */
            message: string;
        };
        /** DocumentMetadata */
        DocumentMetadata: {
            /** Source */
            source: string;
            /** Chunk Index */
            chunk_index: number;
            /** Total Chunks */
            total_chunks: number;
            /** Char Length */
            char_length: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Collection Chunks */
            collection_chunks: number;
            /** Embedding Model */
            embedding_model: string;
            /** Groq Model */
            groq_model: string;
        };
        /** ProcessDocumentResponse */
        ProcessDocumentResponse: {
            /** Success */
            success: boolean;
            /** Pdf Name */
            pdf_name: string;
            /** Chunks Added */
            chunks_added: number;
            /** Text Length */
            text_length: number;
            /** Message */
            message: string;
        };
        /** QueryRequest */
        QueryRequest: {
            /**
             * Query
             * @description Pergunta sobre os documentos
             */
            query: string;
            /**
             * N Results
             * @description Número de chunks a recuperar
             * @default 5
             */
            n_results: number;
            /**
             * Source Filter
             * @description Filtrar por nome do arquivo PDF
             */
            source_filter?: string | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Chunks */
            chunks: components["schemas"]["ChunkResult"][];
            /** Total Found */
            total_found: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    upload_document_documents_upload_post: {
        parameters: {
            query?: {
                /** @description Words per chunk */
                chunk_size?: number;
                /** @description Overlap between chunks */
                overlap?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_documents__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionStatsResponse"];
                };
            };
        };
    };
    clear_collection_documents__delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_document_documents__pdf_name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pdf_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    semantic_search_search__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_search_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
